//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proto_edge_cs_net45
{
    using System;
    using System.Collections.Generic;
    
    public partial class Todo
    {
        public decimal TodoId { get; set; }
        public string Title { get; set; }
        public Nullable<bool> Completed { get; set; }
        public string Description { get; set; }
    }
}
